services:
  - type: web
    name: pdfparser
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_final.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16